-- Aircraft Reference Table
DROP TABLE IF EXISTS acftref;
CREATE TABLE IF NOT EXISTS acftref (
    "CODE" TEXT PRIMARY KEY,
    "MFR" TEXT,
    "MODEL" TEXT,
    "TYPE-ACFT" TEXT,
    "TYPE-ENG" TEXT,
    "AC-CAT" TEXT,
    "BUILD-CERT-IND" TEXT,
    "NO-ENG" INTEGER,
    "NO-SEATS" INTEGER,
    "AC-WEIGHT" TEXT,
    "SPEED" TEXT,
    "TC-DATA-SHEET" TEXT,
    "TC-DATA-HOLDER" TEXT
);

-- Dealer Table
DROP TABLE IF EXISTS dealer;
CREATE TABLE IF NOT EXISTS dealer (
    "CERTIFICATE-NUMBER" TEXT PRIMARY KEY,
    "OWNERSHIP" TEXT,
    "CERTIFICATE-DATE" DATE,
    "EXPIRATION-DATE" DATE,
    "EXPIRATION-FLAG" TEXT,
    "CERTIFICATE-ISSUE-COUNT" INTEGER,
    "NAME" TEXT,
    "STREET" TEXT,
    "STREET2" TEXT,
    "CITY" TEXT,
    "STATE-ABBREV" TEXT,
    "ZIP-CODE" TEXT,
    "OTHER-NAMES-COUNT" INTEGER,
    "OTHER-NAMES-1" TEXT,
    "OTHER-NAMES-2" TEXT,
    "OTHER-NAMES-3" TEXT,
    "OTHER-NAMES-4" TEXT,
    "OTHER-NAMES-5" TEXT,
    "OTHER-NAMES-6" TEXT,
    "OTHER-NAMES-7" TEXT,
    "OTHER-NAMES-8" TEXT,
    "OTHER-NAMES-9" TEXT,
    "OTHER-NAMES-10" TEXT,
    "OTHER-NAMES-11" TEXT,
    "OTHER-NAMES-12" TEXT,
    "OTHER-NAMES-13" TEXT,
    "OTHER-NAMES-14" TEXT,
    "OTHER-NAMES-15" TEXT,
    "OTHER-NAMES-16" TEXT,
    "OTHER-NAMES-17" TEXT,
    "OTHER-NAMES-18" TEXT,
    "OTHER-NAMES-19" TEXT,
    "OTHER-NAMES-20" TEXT,
    "OTHER-NAMES-21" TEXT,
    "OTHER-NAMES-22" TEXT,
    "OTHER-NAMES-23" TEXT,
    "OTHER-NAMES-24" TEXT,
    "OTHER-NAMES-25" TEXT
);

-- Deregistration Table
DROP TABLE IF EXISTS dereg;
CREATE TABLE IF NOT EXISTS dereg (
    "N-NUMBER" TEXT,
    "SERIAL-NUMBER" TEXT,
    "MFR-MDL-CODE" TEXT,
    "STATUS-CODE" TEXT,
    "NAME" TEXT,
    "STREET-MAIL" TEXT,
    "STREET2-MAIL" TEXT,
    "CITY-MAIL" TEXT,
    "STATE-ABBREV-MAIL" TEXT,
    "ZIP-CODE-MAIL" TEXT,
    "ENG-MFR-MDL" TEXT,
    "YEAR-MFR" INTEGER,
    "CERTIFICATION" TEXT,
    "REGION" TEXT,
    "COUNTY-MAIL" TEXT,
    "COUNTRY-MAIL" TEXT,
    "AIR-WORTH-DATE" DATE,
    "CANCEL-DATE" DATE,
    "MODE-S-CODE" TEXT,
    "INDICATOR-GROUP" TEXT,
    "EXP-COUNTRY" TEXT,
    "LAST-ACT-DATE" DATE,
    "CERT-ISSUE-DATE" DATE,
    "STREET-PHYSICAL" TEXT,
    "STREET2-PHYSICAL" TEXT,
    "CITY-PHYSICAL" TEXT,
    "STATE-ABBREV-PHYSICAL" TEXT,
    "ZIP-CODE-PHYSICAL" TEXT,
    "COUNTY-PHYSICAL" TEXT,
    "COUNTRY-PHYSICAL" TEXT,
    "OTHER-NAMES(1)" TEXT,
    "OTHER-NAMES(2)" TEXT,
    "OTHER-NAMES(3)" TEXT,
    "OTHER-NAMES(4)" TEXT,
    "OTHER-NAMES(5)" TEXT,
    "KIT MFR" TEXT,
    "KIT MODEL" TEXT,
    "MODE S CODE HEX" TEXT
);

-- Document Index Table
DROP TABLE IF EXISTS docindex;
CREATE TABLE IF NOT EXISTS docindex (
    "TYPE-COLLATERAL" TEXT,
    "COLLATERAL" TEXT,
    "PARTY" TEXT,
    "DOC-ID" TEXT PRIMARY KEY,
    "DRDATE" DATE,
    "PROCESSING-DATE" DATE,
    "CORR-DATE" DATE,
    "CORR-ID" TEXT,
    "SERIAL-ID" TEXT,
    "DOC-TYPE" TEXT
);

-- Engine Table
DROP TABLE IF EXISTS engine;
CREATE TABLE IF NOT EXISTS engine (
    "CODE" TEXT PRIMARY KEY,
    "MFR" TEXT,
    "MODEL" TEXT,
    "TYPE" TEXT,
    "HORSEPOWER" INTEGER,
    "THRUST" INTEGER
);

-- Master Registry Table
DROP TABLE IF EXISTS master;
CREATE TABLE IF NOT EXISTS master (
    "N-NUMBER" TEXT PRIMARY KEY,
    "SERIAL NUMBER" TEXT,
    "MFR MDL CODE" TEXT,
    "ENG MFR MDL" TEXT,
    "YEAR MFR" INTEGER,
    "TYPE REGISTRANT" TEXT,
    "NAME" TEXT,
    "STREET" TEXT,
    "STREET2" TEXT,
    "CITY" TEXT,
    "STATE" TEXT,
    "ZIP CODE" TEXT,
    "REGION" TEXT,
    "COUNTY" TEXT,
    "COUNTRY" TEXT,
    "LAST ACTION DATE" DATE,
    "CERT ISSUE DATE" DATE,
    "CERTIFICATION" TEXT,
    "TYPE AIRCRAFT" TEXT,
    "TYPE ENGINE" TEXT,
    "STATUS CODE" TEXT,
    "MODE S CODE" TEXT,
    "FRACT OWNER" TEXT,
    "AIR WORTH DATE" DATE,
    "OTHER NAMES(1)" TEXT,
    "OTHER NAMES(2)" TEXT,
    "OTHER NAMES(3)" TEXT,
    "OTHER NAMES(4)" TEXT,
    "OTHER NAMES(5)" TEXT,
    "EXPIRATION DATE" DATE,
    "UNIQUE ID" TEXT,
    "KIT MFR" TEXT,
    "KIT MODEL" TEXT,
    "MODE S CODE HEX" TEXT
);

-- Reserved Table
DROP TABLE IF EXISTS reserved;
CREATE TABLE IF NOT EXISTS reserved (
    "N-NUMBER" TEXT PRIMARY KEY,
    "REGISTRANT" TEXT,
    "STREET" TEXT,
    "STREET2" TEXT,
    "CITY" TEXT,
    "STATE" TEXT,
    "ZIP CODE" TEXT,
    "RSV DATE" DATE,
    "TR" TEXT,
    "EXP DATE" DATE,
    "N-NUM-CHG" TEXT,
    "PURGE DATE" DATE
);